apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
 # progressDeadlineSeconds: 3600
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
         # image: "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          image: fabricioveronez/web-page:green
          ports:
            - containerPort: 8080
        
